version: '3.0'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    links:
      - redis
    environment:
      HTTP_PORT: 8080
      REDIS_HOST: redis
  redis:
    image: "redis:3.2-alpine"
